spring.application.name=songrec

spring.profiles.active=prod

# JPA ?? (???? update ??? ??)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.access-exp-min=${JWT_ACCESS_EXP_MIN:60}
jwt.refresh-exp-days=${JWT_REFRESH_EXP_DAYS:14}

spotify.client-id=${SPOTIFY_CLIENT_ID}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-5.4
openai.base-url=https://api.openai.com/v1

server.forward-headers-strategy=framework

aws.s3.bucket=noraemoa-thumb-uploads
aws.s3.region=ap-northeast-2
aws.s3.base-url=https://noraemoa-thumb-uploads.s3.ap-northeast-2.amazonaws.com