spring.application.name=songrec
# JDBC URL - ?? ?? DB ?? ??
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ?? (???? update ??? ??)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.access-exp-min=${JWT_ACCESS_EXP_MIN:60}
jwt.refresh-exp-days=${JWT_REFRESH_EXP_DAYS:14}